###

grpcurl -proto api/protobuf/protofiles/sso/auth.proto -plaintext -d '{"email": "alexqwerty35@yandex.ru"}' localhost:8070 auth.AuthService.SendForgetPasswordMessage

###

grpcurl -proto api/protobuf/protofiles/sso/auth.proto -plaintext -d '{"forgetPasswordToken": "MzE","newPassword": "Qwer1234@"}' localhost:8070 auth.AuthService.ForgetPassword

###

grpcurl -proto api/protobuf/protofiles/sso/users.proto -plaintext -d '{"pagination": {"limit": 2,"offset": 0}}' localhost:8070 users.UsersService.GetUsers

###

grpcurl -proto api/protobuf/protofiles/sso/auth.proto -plaintext -d '{"displayName": "Сука крашенная","email": "john.doe@example.com","password": "securePassword123!"}' localhost:8070 auth.AuthService.Register

